import React, {useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight,ArrowUpRight,Bookmark,Check,ChevronRight,ExternalLink,FileText,GitBranch,Layers,Link,Play,Plus,Radio,RotateCcw,Search,Settings2,Sparkles,X,Inbox,BookOpen,Compass,CheckCircle2,LoaderCircle} from 'lucide-react';
import {initialState,collect,generate,story,sources,profiles,type State,type ProfileId,type Run,type Entry} from './model';
import './style.css';
const nav=[['home','体验总览',Compass],['inbox','转发与解析',Inbox],['topics','关注主题',Layers],['collect','收集现场',Radio],['profiles','博主风格',Sparkles],['compose','内容编排',GitBranch],['feed','我的 Feed',BookOpen]] as const;
const slides = [
 {page:'home',chapter:'产品概念',title:'把关注，织成见解。',body:'为程序员的学习与工作，把跨平台的线索变成持续更新、带有个人风格的阅读内容。',why:'从一条转发开始，让一个值得关注的问题持续生长。',hint:'先看全貌，再逐页展开。'},
 {page:'inbox',chapter:'转发与理解',title:'一次转发，发现一个主题。',body:'在手机或其他平台发现好内容，转发给 Feedloom。解析保留原文和来源，并给出 Topic 推荐。',why:'人来决定关注什么，系统帮助识别线索。',hint:'右侧模拟手机分享后的接收界面。'},
 {page:'topics',chapter:'一次配置',title:'决定关注什么，也决定怎么读。',body:'在 Topic 中选择来源、收集频率和博主风格。后面的收集、整理与生成，都沿用这份配置。',why:'风格提前选好，不必每次收集后重新操作。',hint:'可以点选主题或风格，感受配置方式。'},
 {page:'profiles',chapter:'表达风格',title:'从博主的文章，学会组织信息。',body:'分析一组历史内容，提取开场方式、信息结构和表达习惯，形成可复用的 Creator Profile。',why:'学习如何表达；事实仍然来自本次收集。',hint:'切换两位虚构博主，查看样例与规则。'},
 {page:'collect',chapter:'持续收集',title:'把分散的信息，先收集完整。',body:'按 Topic 定时访问不同平台，保存原文、讨论和项目信息。每次运行都有明确的来源与结果。',why:'收集重在覆盖；原文可能很长、重复，也可能互相补充。',hint:'示例已就绪，也可以模拟一次收集。'},
 {page:'compose',chapter:'内容整理',title:'收集得全，还要讲得好。',body:'把相关线索放在一起，抽取重要信息，按选定风格组织成一份更好读的 Feed。',why:'这一步把素材变成内容，而非把链接换个地方堆放。',hint:'最终产品自动连续完成；这里拆开展示。'},
 {page:'feed',chapter:'阅读与依据',title:'读到重点，也能回到来源。',body:'用熟悉的表达读懂变化、价值与下一步。需要判断时，再展开原始材料和收集记录。',why:'Feed 是阅读入口，生成文字不能替代原始证据。',hint:'可以打开证据抽屉，看看一份内容的来路。'}
];
const key='feedloom-story-v2';
function read():State{try{const s=JSON.parse(localStorage.getItem(key)||'null');if(s?.topics?.length&&Array.isArray(s.entries)&&typeof s.serial==='number')return s;}catch{}return initialState();}
function App(){
 const [state,setState]=useState<State>(read),[page,setPage]=useState(location.hash.slice(1)||'home'),[topicId,setTopicId]=useState('t1'),[profile,setProfile]=useState<ProfileId>('practical'),[runId,setRunId]=useState('r0'),[entryId,setEntryId]=useState('f0'),[scenario,setScenario]=useState<Run['status']>('success'),[continuous,setContinuous]=useState(false),[notice,setNotice]=useState(''),[evidence,setEvidence]=useState<Entry|null>(null),[sourceId,setSourceId]=useState<string|null>(null),[creating,setCreating]=useState(false),[name,setName]=useState(''),[job,setJob]=useState<{type:'parse'|'collect'|'profile'|'generate';step:number;topicId:string;profile:ProfileId;runId:string;scenario:Run['status'];continuous:boolean}|null>(null);
 const slideIndex=Math.max(0,slides.findIndex(s=>s.page===page));
 const slide=slides[slideIndex];
 const topic=state.topics.find(t=>t.id===topicId)||state.topics[0], run=state.runs.find(r=>r.id===runId)||state.runs[0], entry=state.entries.find(e=>e.id===entryId)||state.entries[0];
 const go=(p:string)=>{location.hash=p;setPage(p);window.scrollTo(0,0)};
 useEffect(()=>{document.querySelector('main')?.scrollTo(0,0)},[page]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setEvidence(null);setSourceId(null);setCreating(false)}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
 useEffect(()=>{const f=()=>setPage(location.hash.slice(1)||'home');window.addEventListener('hashchange',f);return()=>window.removeEventListener('hashchange',f)},[]);
 useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(state))}catch{setNotice('浏览器未允许保存；本次操作仍可继续。')}},[state]);
 useEffect(()=>{if(notice){const t=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(t)}},[notice]);
 const stages=job?.type==='parse'?['接收分享内容','解析正文与媒体','识别主题线索','内容已就绪']:job?.type==='profile'?['读取三篇样例','识别叙述结构','提取表达习惯','形成风格规则']:job?.type==='generate'?['读取收集结果与风格','合并相同信息','组织重点与局限','检查来源引用']:['读取 Topic 配置','逐个平台收集','筛选相关内容','保留来源与运行记录'];
 useEffect(()=>{if(!job)return;const t=setTimeout(()=>{if(job.step<3){setJob({...job,step:job.step+1});return;}
 if(job.type==='parse'){setState(s=>({...s,parsed:true}));setNotice('模拟解析完成，发现两个推荐 Topic。')}
 if(job.type==='profile'){setState(s=>({...s,extracted:Array.from(new Set([...s.extracted,job.profile]))}));setNotice('模拟提取完成，可将这个风格绑定到 Topic。')}
 if(job.type==='collect'){const next=collect(state,job.topicId,job.scenario);setState(next);setRunId(next.runs[0].id);if(job.continuous&&next.runs[0].sourceIds.length){setJob({...job,type:'generate',step:0,runId:next.runs[0].id});go('compose');return;}setNotice(next.runs[0].sourceIds.length?'收集完成，可以查看素材或继续生成 Feed。':'本次没有可生成的素材，请查看来源状态。')}
 if(job.type==='generate'){const next=generate(state,job.runId);setState(next);setEntryId(next.entries[0].id);setNotice('模拟 Feed 已生成，引用已保留。');go('feed')}
 setJob(null);
 },850);return()=>clearTimeout(t)},[job,state]);
 function start(type:NonNullable<typeof job>['type']){if(job)return;setJob({type,step:0,topicId:topic.id,profile,runId:run.id,scenario,continuous});}
 function updateTopic(patch:Partial<typeof topic>){setState(s=>({...s,topics:s.topics.map(t=>t.id===topic.id?{...t,...patch}:t)}))}
 function showRun(id:string){setRunId(id);go('collect')}
 const action=(text:string,fn:()=>void,secondary=false,disabled=false)=><button className={secondary?'button secondary':'button'} onClick={fn} disabled={disabled}>{text}<ArrowRight size={16}/></button>;
 const badge=<span className="demo"><span/>模拟数据 · 本地体验</span>;
 const intro=(eyebrow:string,title:string,description:string)=><div className="page-heading"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>;
 const explain=(title:string,text:string)=><aside className="explain"><Sparkles size={18}/><div><strong>{title}</strong><p>{text}</p></div></aside>;
 const progress=job&&<div className="progress" role="status"><div className="row"><strong><LoaderCircle className="spin" size={17}/> {job.type==='parse'?'模拟解析':job.type==='profile'?'模拟风格提取':job.type==='collect'?'模拟收集':'模拟 Feed 生成'}</strong><button className="text-button" onClick={()=>{setJob(null);setNotice('已取消模拟运行，已有内容保持不变。')}}>取消运行</button></div><div className="stages">{stages.map((s,i)=><div key={s} className={i<=job.step?'active':''}><span>{i<job.step?<Check size={13}/>:i+1}</span>{s}</div>)}</div></div>;
 const sourceCards=(ids:string[])=><div className="source-grid">{sources.filter(s=>ids.includes(s.id)).map(s=><button className="source-card" key={s.id} onClick={()=>setSourceId(s.id)}><div className={`source-art ${s.color}`}><span>{s.platform}</span><div>{s.id==='s2'?<><code>context /</code><code> ├─ entrypoints</code><code> └─ boundaries</code></>:s.id==='s1'?<><b>先给 AI<br/>一张项目地图。</b><small>开发手记 / 014</small></>:<><FileText size={30}/><b>{s.kind}与观点</b></>}</div></div><div className="source-copy"><small>{s.kind} · 示例来源</small><h3>{s.title}</h3><p>{s.author}</p></div></button>)}</div>;
 return <div className="presentation"><div className="deck-top"><a href="#home" className="brand"><span className="brand-icon">▥</span>feedloom</a><span>PRODUCT PITCH <i/> 产品概念讲解</span><small>虚构样例 · 界面概念展示</small><button className="text-button" onClick={()=>{setJob(null);setState(initialState());setTopicId("t1");setProfile("practical");setRunId("r0");setEntryId("f0");setScenario("success");setContinuous(false);go("home");setNotice("已恢复初始示例。")}}><RotateCcw size={12}/>重置演示</button></div><div className="deck-layout"><aside className="narrative"><div className="slide-count">{String(slideIndex+1).padStart(2,'0')} <span>/ 07</span></div><div className="eyebrow">{slide.chapter}</div><h1>{slide.title}</h1><p className="narrative-body">{slide.body}</p><div className="narrative-why"><span>为什么这样做</span><p>{slide.why}</p></div><div className="narrative-hint"><span>界面示意</span><p>{slide.hint}</p></div><div className="deck-controls"><button disabled={slideIndex===0} onClick={()=>go(slides[slideIndex-1].page)} aria-label="上一页">←</button><button className="deck-next" onClick={()=>go(slides[(slideIndex+1)%slides.length].page)}>{slideIndex===6?'回到开头':'下一页'}<ArrowRight size={17}/></button></div></aside><div className="demo-window"><div className="window-bar"><div className="window-dots"><i/><i/><i/></div><span>feedloom / {slide.chapter}</span><span className="window-status">设计示意 · 少量交互</span></div><div className="app"><aside className="sidebar"><a className="brand" href="#home"><span className="brand-icon">▥</span>feedloom<span className="beta">DEMO</span></a><div className="workspace"><div className="avatar">H</div><div><strong>huggon1 的学习空间</strong><small>从关注，到自己的见解</small></div></div><div className="nav-label">探索工作流</div><nav>{nav.map(([id,label,Icon])=><button key={id} onClick={()=>go(id)} className={page===id?'selected':''}><Icon size={18}/>{label}{page===id&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-note"><span className="tiny-label">ABOUT THIS DEMO</span><p>把分散的操作放在一起，<br/>看看内容如何成为见解。</p><a href="#home">了解这段流程 <ArrowUpRight size={14}/></a></div><button className="reset" onClick={()=>{if(window.confirm('重置所有示例数据和本地操作？')){setJob(null);setState(initialState());setTopicId('t1');setProfile('practical');setRunId('r0');setEntryId('f0');setEvidence(null);setSourceId(null);setCreating(false);setName('');setScenario('success');setContinuous(false);go('home');setNotice('已恢复初始示例。')}}}><RotateCcw size={15}/>重置 Demo</button></aside>
 <div className="shell"><header><div className="breadcrumb">学习空间 <ChevronRight size={13}/><span>{nav.find(n=>n[0]===page)?.[1]}</span></div><div className="header-right"><div className="search-placeholder" aria-label="搜索，演示占位"><Search size={15}/>搜索内容、主题…<small>未开放</small></div>{badge}<div className="avatar small">H</div></div></header><main>
 {page==='home'&&<>{intro('YOUR PERSONAL SIGNAL, WOVEN TOGETHER','关注很多，读懂更少。','把散落在不同平台的信息，变成一份值得读的个人 Feed。')}<section className="hero"><div className="hero-copy"><span className="pill">为程序员的学习与构建准备</span><h2>从一个收藏，<br/>长出持续的关注。</h2><p>转发一条好内容，发现一个主题。<br/>让后续的信息自己汇集，按你喜欢的方式讲清楚。</p>{action('展开这段故事',()=>go('inbox'))}<small>准备好的虚构样例 · 无需账号或配置</small></div><div className="hero-visual"><div className="floating-source one"><span className="platform-dot rose">小</span><div>一篇开发手记<small>“先给 AI 一张项目地图”</small></div></div><div className="floating-source two"><span className="platform-dot ink">G</span><div>一个开源项目<small>Patchwork / context</small></div></div><div className="woven-line"/><div className="mini-feed"><span className="tiny-label">YOUR FEED · 林序风格</span><h3>给 AI 一张项目地图，<br/>再让它动手。</h3><p>从项目入口、边界和验证命令开始。<br/>一个可以在今天试试的小改动。</p><div><span>3 条示例依据</span><ArrowUpRight size={17}/></div></div></div></section><div className="section-title"><h2>一条内容，如何走到你面前</h2><span>可以从任意一站开始探索</span></div><div className="journey">{[['inbox','01','收到 & 理解','转发内容，发现关注线索'],['topics','02','设定关注','主题、来源、频率与风格'],['collect','03','持续收集','从不同平台找到完整信息'],['compose','04','整理 & 表达','提炼重点，保留证据'],['feed','05','认真阅读','读得懂，也知道下一步']].map(([p,n,t,d])=><button onClick={()=>go(p)} key={p}><span>{n}</span><h3>{t}</h3><p>{d}</p><ArrowRight size={17}/></button>)}</div><div className="home-bottom"><div><div className="section-title"><h2>你的关注，持续生长</h2><button className="text-button" onClick={()=>go('topics')}>管理主题 <ArrowRight size={14}/></button></div><div className="topic-chips">{state.topics.map(t=><button key={t.id} onClick={()=>{setTopicId(t.id);go('topics')}}><span>#</span>{t.name}<ArrowUpRight size={14}/></button>)}</div></div><aside className="small-explain"><strong>为什么把流程拆开？</strong><p>真正使用时，转发可能发生在手机上；Topic 配好风格后，收集到生成会连续完成。这里把每一站展开，让你看见它们如何协作。</p></aside></div></>}
 {page==='inbox'&&<>{intro('01 / CAPTURE & UNDERSTAND','好内容，是一个开始。','模拟一次从其他平台转发内容的过程，看看 Feedloom 如何理解它。')}<div className="split"><section className="panel"><div className="section-title"><h2>在其他平台发现</h2><span className="tag">转发模拟器</span></div><div className="social-post"><div className="row"><span className="platform-dot rose">小</span><strong>林序的开发手记</strong><small>虚构博主</small></div><div className="post-art"><small>DEV NOTES / 014</small><h2>先给 AI<br/>一张项目地图。</h2><code>入口 → 边界 → 验证</code></div><h3>{sources[0].title}</h3><p>{sources[0].body}</p><div className="tags"># AI 编程工具　# 产品构建</div></div>{action(state.parsed?'重新模拟转发':'转发给 Feedloom',()=>start('parse'),false,!!job)}<p className="muted">此处代替手机分享入口，只使用内置示例内容。</p></section><section className="panel"><div className="section-title"><h2>Feedloom 接收后</h2><span className="tag">{state.parsed?'已解析':'等待转发'}</span></div>{job?.type==='parse'?progress:!state.parsed?<div className="empty"><Inbox size={38}/><h3>把感兴趣的内容带进来</h3><p>点击左侧转发按钮，查看解析结果和 Topic 推荐。</p></div>:<><div className="success-line"><CheckCircle2 size={18}/>正文、图片、作者与来源已保留</div><dl><dt>原始内容</dt><dd>{sources[0].title}</dd><dt>平台 / 类型</dt><dd>小红书 / 图文 · 模拟</dd><dt>解析摘要</dt><dd>通过项目说明改善 AI 编程上下文，同时保留测试和人工判断。</dd></dl><h3>从内容中发现 Topic</h3><p className="muted">这些是模拟推荐，最终由你决定关注什么。</p><div className="recommendations">{state.topics.map(t=><button key={t.id} className={state.assigned===t.id?'picked':''} onClick={()=>{setState(s=>({...s,assigned:t.id}));setTopicId(t.id)}}><span># {t.name}</span>{state.assigned===t.id?<Check size={16}/>:<Plus size={16}/>}</button>)}</div>{state.assigned&&<>{explain('已经有了一个持续关注的方向','这条内容会归入选中的 Topic。接下来决定从哪里收集、多久收集一次，以及用什么风格阅读。')}{action('配置这个 Topic',()=>go('topics'))}</>}</>}</section></div></>}
 {page==='topics'&&<>{intro('02 / FOLLOW A QUESTION','把兴趣，变成持续关注。','一次配置主题、来源、频率和表达风格。之后，收集与 Feed 生成沿着这份配置连续完成。')}<div className="topic-layout"><section className="topic-list">{state.topics.map(t=><button key={t.id} className={t.id===topic.id?'active':''} onClick={()=>setTopicId(t.id)}><span>#</span><div><strong>{t.name}</strong><small>{t.enabled?t.frequency:'已暂停'} · {profiles[t.profile].name.split(' · ')[1]}</small></div><ChevronRight size={16}/></button>)}<button onClick={()=>setCreating(true)}><Plus size={17}/>新建 Topic</button></section><section className="panel"><div className="section-title"><h2># {topic.name}</h2><span className="tag">配置自动保存</span></div><label>关注什么<textarea value={topic.description} onChange={e=>updateTopic({description:e.target.value})}/></label><label>从哪里收集</label><div className="platforms">{['GitHub','小红书','Hacker News','产品社区','技术博客'].map(p=><label key={p}><input type="checkbox" checked={topic.platforms.includes(p)} onChange={e=>updateTopic({platforms:e.target.checked?[...topic.platforms,p]:topic.platforms.filter(x=>x!==p)})}/>{p}</label>)}</div><div className="two-fields"><label>收集频率<select value={topic.frequency} onChange={e=>updateTopic({frequency:e.target.value})}><option>每天 09:00</option><option>每周一 09:00</option><option>每周五 18:00</option></select></label><label>计划状态<select value={topic.enabled?'on':'off'} onChange={e=>updateTopic({enabled:e.target.value==='on'})}><option value="on">启用</option><option value="off">暂停</option></select></label></div><label>这份 Feed，用谁的表达风格？</label><div className="profile-options">{(Object.keys(profiles) as ProfileId[]).map(id=><button key={id} className={topic.profile===id?'picked':''} onClick={()=>updateTopic({profile:id})}><div className={`avatar ${id==='brief'?'violet':''}`}>{profiles[id].initial}</div><strong>{profiles[id].name}</strong><small>{profiles[id].tag}</small>{topic.profile===id&&<Check size={17}/>}</button>)}</div><button className="text-button" onClick={()=>{setProfile(topic.profile);go('profiles')}}>这个风格是怎么提取的？ <ArrowUpRight size={15}/></button>{explain('配好一次，后面连贯发生','最终产品会按计划收集、整理并生成 Feed。Demo 不会在后台定时执行；下一站可以模拟一次计划运行，也可以逐段查看。')}{action('去收集现场',()=>go('collect'),false,topic.platforms.length===0)}{!topic.platforms.length&&<p className="error">至少选择一个来源平台。</p>}{state.assigned===topic.id&&<button className="linked-record" onClick={()=>setSourceId('s1')}><Link size={16}/>来自你的转发：{sources[0].title}<ArrowUpRight size={16}/></button>}</section></div></>}
 {page==='collect'&&<>{intro('03 / GATHER THE SIGNAL','先收集完整，再提炼重要。','原文、讨论、项目说明各有侧重。把它们放在一起，才有整理和判断的基础。')}<div className="toolbar"><label>当前 Topic<select value={topic.id} onChange={e=>setTopicId(e.target.value)}>{state.topics.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>演示场景<select value={scenario} onChange={e=>setScenario(e.target.value as Run['status'])}><option value="success">成功</option><option value="partial">部分来源不可用</option><option value="empty">无相关结果</option><option value="failed">来源访问失败</option></select></label><label className="check-label"><input type="checkbox" checked={continuous} onChange={e=>setContinuous(e.target.checked)}/>连续生成 Feed</label>{action('立即模拟一次',()=>start('collect'),false,!!job||!topic.platforms.length)}</div><p className="muted">计划：{topic.enabled?topic.frequency:'已暂停，仍可手动演示'} · 绑定风格：{profiles[topic.profile].name} · 时间仅用于展示配置</p>{job?.type==='collect'&&progress}<div className="section-title"><h2>收集运行</h2><span>点击记录查看当次输入与结果</span></div><div className="run-tabs">{state.runs.map(r=><button key={r.id} className={run.id===r.id?'active':''} onClick={()=>setRunId(r.id)}>{r.id} · {state.topics.find(t=>t.id===r.topicId)?.name}<span>{({success:'成功',partial:'部分成功',empty:'无结果',failed:'失败'})[r.status]}</span></button>)}</div><section className="panel"><div className="section-title"><h2>{state.topics.find(t=>t.id===run.topicId)?.name} <small>/ {run.id}</small></h2><button className="text-button" onClick={()=>{setTopicId(run.topicId);go('topics')}}>查看 Topic <ArrowUpRight size={14}/></button></div><div className="coverage">{run.platforms.map((p,i)=><div key={p}><span className="platform-dot">{p[0]}</span><strong>{p}</strong><small>{run.status==='failed'?'访问失败':run.status==='partial'&&i===run.platforms.length-1?'暂时不可用':`${sources.filter(s=>run.sourceIds.includes(s.id)&&s.platform===p).length} 条相关内容`}</small></div>)}</div>{run.sourceIds.length?sourceCards(run.sourceIds):<div className="empty"><Radio size={30}/><h3>{run.status==='failed'?'来源访问失败，未生成内容':'这次没有发现相关内容'}</h3><p>{run.status==='failed'?'示例来源暂时不可用。选择成功场景可重新模拟。':'可以调整 Topic 的来源范围，再模拟一次收集。'}</p></div>}{run.sourceIds.length>0&&<>{explain('收集结果，还不是一份好读的 Feed','这里保留了较完整的原文，信息有重叠，也有观点和限制。下一步会抽取重要内容、组织叙述，并按预先选好的博主风格表达。')}{action('展开内容编排过程',()=>go('compose'))}</>}</section></>}
 {page==='profiles'&&<>{intro('STYLE / LEARN HOW TO TELL IT','学的是表达方式。','从博主的历史内容中提取组织信息的习惯，让收集到的素材拥有一致、好读的表达。')}<div className="profile-tabs">{(Object.keys(profiles) as ProfileId[]).map(id=><button className={profile===id?'active':''} onClick={()=>setProfile(id)} key={id}><div className={`avatar ${id==='brief'?'violet':''}`}>{profiles[id].initial}</div><strong>{profiles[id].name}</strong><span>虚构博主</span></button>)}</div><div className="split"><section><div className="section-title"><h2>从这三篇内容中学习</h2><span>内置样例</span></div>{profiles[profile].samples.map((s,i)=><article className="sample" key={s.title}><small>样例 0{i+1} · {profiles[profile].name}</small><h3>{s.title}</h3><p>{s.text}</p></article>)}</section><section className="panel"><span className="eyebrow">CREATOR PROFILE</span><h2>{profiles[profile].tag}</h2><p>{profiles[profile].description}</p>{job?.type==='profile'?progress:<div className="rules">{profiles[profile].rules.map((r,i)=><div key={r}><span>0{i+1}</span><strong>{r}</strong><small>依据：样例 {i+1}</small></div>)}</div>}{action('模拟提取个人风格',()=>start('profile'),false,!!job)}{explain('风格影响组织与语气，不改变事实','这两份预设来自上方虚构样例。模拟提取会回放分析阶段，输出确定的规则；不会调用模型或分析真实博主。')}<label>应用到 Topic<select value={topic.id} onChange={e=>setTopicId(e.target.value)}>{state.topics.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{action('将这个风格用于该 Topic',()=>{updateTopic({profile});setNotice('已绑定风格，后续收集会使用这份配置。');go('topics')},true,!!job)}</section></div></>}
 {page==='compose'&&<>{intro('04 / EDIT FOR A HUMAN','信息收集得全，也要讲得好。','把重复的线索合在一起，保留重要事实与局限，再用你选择的风格组织成一篇能读下去的内容。')}<div className="compose-input"><div><span className="tiny-label">本次输入</span><h3>{state.topics.find(t=>t.id===run.topicId)?.name}</h3><button className="text-button" onClick={()=>showRun(run.id)}>{run.id} · {run.sourceIds.length} 条来源 <ArrowUpRight size={14}/></button></div><Plus size={20}/><div><span className="tiny-label">收集时绑定的风格</span><h3>{profiles[run.profile].name}</h3><button className="text-button" onClick={()=>{setProfile(run.profile);go('profiles')}}>查看表达规则 <ArrowUpRight size={14}/></button></div><ArrowRight size={22}/><div><span className="tiny-label">生成结果</span><h3>一份可读、可追溯的 Feed</h3><small>保留来源和本次收集记录</small></div></div>{job?.type==='generate'&&progress}<div className="split"><section className="panel raw"><div className="section-title"><h2>收集到的素材</h2><span className="tag">完整 · 分散 · 有重叠</span></div>{sources.filter(s=>run.sourceIds.includes(s.id)).map(s=><article key={s.id}><small>{s.platform} / {s.id}</small><h3>{s.title}</h3><p>{s.body}</p></article>)}{!run.sourceIds.length&&<p>本次运行没有可用素材，请先完成一次有结果的收集。</p>}</section><section className="panel editorial"><span className="eyebrow">THE EDITORIAL PASS</span><h2>从原始信息，到阅读体验</h2>{[['找到共同问题','围绕 Topic 筛选重点，重复信息放在一起。'],['组织一条叙述','按 Profile 决定如何开场、解释和收尾。'],['留住边界与依据','个人经验不写成普遍结论，每段能回到来源。']].map(([t,d],i)=><div className="editor-step" key={t}><span>{i+1}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}{action('模拟生成 Feed',()=>start('generate'),false,!!job||!run.sourceIds.length)}<p className="muted">使用固定模板整理示例素材，不调用真实模型。</p></section></div></>}
 {page==='feed'&&<>{intro('05 / YOUR PERSONAL FEED','少一点信息堆积，多一点收获。','围绕你的关注，用熟悉的表达，把值得了解的事讲清楚。')}<div className="feed-layout"><div><div className="feed-selection">{state.entries.map(e=><button key={e.id} className={e.id===entry.id?'active':''} onClick={()=>setEntryId(e.id)}>{state.topics.find(t=>t.id===e.topicId)?.name} · {profiles[e.profile].name.split(' · ')[1]}<small>{e.id==='f0'?'预置示例':e.id}</small></button>)}</div>{entry&&(()=>{const text=story(entry);return <article className="feed-article"><div className="feed-meta"><span className="tag">{state.topics.find(t=>t.id===entry.topicId)?.name}</span><span>模拟生成 · {entry.id}</span></div><h2>{text.title}</h2><p className="feed-intro">{text.intro}</p><div className="byline"><div className="avatar">{profiles[entry.profile].initial}</div><div><strong>{profiles[entry.profile].name}</strong><small>依据 {entry.sourceIds.length} 条示例内容整理</small></div><button aria-label="收藏 Feed" className={entry.bookmarked?'icon-button saved':'icon-button'} onClick={()=>setState(s=>({...s,entries:s.entries.map(e=>e.id===entry.id?{...e,bookmarked:!e.bookmarked}:e)}))}><Bookmark size={20}/></button></div>{entry.sourceIds.some(id=>["s1","s2","s3"].includes(id))&&<div className="article-illustration"><div><small>CONTEXT FIRST</small><b>入口</b><span>知道从哪里开始</span></div><ArrowRight/><div><small>KEEP THE BOUNDARY</small><b>边界</b><span>知道什么要保留</span></div><ArrowRight/><div><small>MAKE IT VERIFIABLE</small><b>验证</b><span>知道结果是否可靠</span></div></div>}{text.sections.map((s,i)=><section key={s.id}><h3><span>{String(i+1).padStart(2,'0')}</span>{s.title}</h3><p>{s.body}</p><button className="citation" onClick={()=>setSourceId(s.id)}>[{i+1}] 查看原始依据 <ArrowUpRight size={12}/></button></section>)}<aside className="next-action"><span className="eyebrow">可以从这里开始</span><h3>拿一个小任务试试。</h3><p>{text.next}</p></aside><footer><span>示例内容，不代表真实产品发布或评测</span><button className="text-button" onClick={()=>setEvidence(entry)}>查看全部依据 <Link size={15}/></button></footer></article>})()}</div><aside className="feed-side"><span className="tiny-label">BEHIND THIS FEED</span><h3>一份内容的来路</h3><button onClick={()=>{setTopicId(entry.topicId);go('topics')}}><Layers size={17}/><div><small>关注主题</small>{state.topics.find(t=>t.id===entry.topicId)?.name}</div><ChevronRight size={16}/></button><button onClick={()=>showRun(entry.runId)}><Radio size={17}/><div><small>收集记录</small>{entry.runId} · {entry.sourceIds.length} 条来源</div><ChevronRight size={16}/></button><button onClick={()=>{setProfile(entry.profile);go('profiles')}}><Sparkles size={17}/><div><small>表达风格</small>{profiles[entry.profile].name}</div><ChevronRight size={16}/></button>{action('打开证据抽屉',()=>setEvidence(entry),true)}<p>生成内容是阅读入口。原始素材始终保留，方便你继续了解和判断。</p><div className="style-note"><strong>想换一种读法？</strong><p>到 Topic 修改风格，再运行一次收集与生成，就能看到同一组素材的另一种表达。</p><button className="text-button" onClick={()=>{setTopicId(entry.topicId);go('topics')}}>调整 Topic 风格 <ArrowRight size={14}/></button></div></aside></div></>}
 {!nav.some(n=>n[0]===page)&&<div className="empty"><h1>这个页面不存在</h1>{action('返回体验总览',()=>go('home'))}</div>}
 </main><div className="app-footer">FEEDLOOM / PRODUCT PITCH<span>所有平台内容、博主与运行均为虚构示例</span></div></div>
 {notice&&<div className="toast" role="status"><CheckCircle2 size={17}/>{notice}</div>}
 {(evidence||sourceId||creating)&&<div className="overlay" onClick={()=>{setEvidence(null);setSourceId(null);setCreating(false)}}><section role="dialog" aria-modal="true" aria-label={creating?'新建 Topic':sourceId?'原始内容':'生成依据'} className="drawer" onClick={e=>e.stopPropagation()}><button autoFocus className="close icon-button" aria-label="关闭" onClick={()=>{setEvidence(null);setSourceId(null);setCreating(false)}}><X/></button>{creating?<><span className="eyebrow">FOLLOW SOMETHING NEW</span><h2>新建 Topic</h2><label>主题名称<input value={name} onChange={e=>setName(e.target.value)} placeholder="例如：开发者工具" maxLength={40}/></label><p>新主题可以配置所有来源；没有匹配示例时，收集会明确显示无结果。</p>{action('创建并配置',()=>{const id=`t${state.serial+10}`;setState(s=>({...s,serial:s.serial+1,topics:[...s.topics,{id,name:name.trim(),description:'',profile:'practical',frequency:'每天 09:00',platforms:['GitHub'],enabled:true}]}));setTopicId(id);setCreating(false);setName('')},false,!name.trim())}</>:sourceId?(()=>{const s=sources.find(x=>x.id===sourceId)!;return <><span className="eyebrow">ORIGINAL SOURCE / {s.id}</span><h2>{s.title}</h2><p>{s.platform} · {s.author}</p><span className="tag">虚构原始内容 · {s.kind}</span><div className={`source-art detail-art ${s.color}`}><b>{s.title}</b></div><p className="source-body">{s.body}</p><dl><dt>来源标识</dt><dd>demo://source/{s.id}（示例引用，不是外部网址）</dd><dt>记录时间</dt><dd>2026-09-10 09:00 · 固定示例时间</dd><dt>相关 Topic</dt><dd>{s.topic}</dd></dl>{evidence&&<button className="text-button" onClick={()=>setSourceId(null)}>返回全部依据</button>}</>})():evidence&&<><span className="eyebrow">EVIDENCE / {evidence.id}</span><h2>每一个重点，都有来处。</h2><p>以下是生成这份 Feed 时实际使用的示例输入。</p>{sources.filter(s=>evidence.sourceIds.includes(s.id)).map((s,i)=><button className="evidence-row" key={s.id} onClick={()=>setSourceId(s.id)}><span>0{i+1}</span><div><small>{s.platform} · {s.id}</small><h3>{s.title}</h3></div><ArrowUpRight size={18}/></button>)}{action(`查看收集运行 ${evidence.runId}`,()=>{showRun(evidence.runId);setEvidence(null)},true)}</>}</section></div>}
 </div></div></div><nav className="deck-nav">{slides.map((s,i)=><button key={s.page} className={s.page===page?'active':''} onClick={()=>go(s.page)}><span>{String(i+1).padStart(2,'0')}</span>{s.chapter}</button>)}</nav></div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
